### ISSUE TITLE
Minimize before the screen selection tool

### ISSUE THREAD

**Issue by Dumschwaetzer** [DDoSolitary/BarcodeReader#4]
Your tool worked out great for me. You might want to fix the NPE that occurs if you just hit Enter in the screen selection tool. Why do we even need to hit Enter?
Minimizing the tool before going into that mode would make sense for me, too.

**Comment by DDoSolitary** [comment]
>  Minimizing the tool before going into that mode would make sense for me, too.

It's a bit harder than I thought. After the call to Window.Hide() returns, the window hasn't yet fully disappeared from screen but is showing the animation. I don't know how to find the correct time to take the screenshot.

> You might want to fix the NPE that occurs if you just hit Enter in the screen selection tool.

I'm unable to reproduce this bug. Could you please provide some more details, like the version of BarcodeReader and Windows, and the exact step to reproduce it?
